sudo: required
services:
  - docker

script:
  - echo "Build local image"
  - docker build -t dns .
  - docker images
  - echo "Run local image"
  - docker run -d --name my-dns dns
  # - docker run -d -p 53:53 --name my-dns dns
  - docker ps -a
  - docker logs my-dns
  - docker exec -it my-dns named -v
  - docker exec -it my-dns dig googole.com IN A
  - docker stop my-dns  
  - echo "Testing public image on Docker Hub"
  - docker run -d --name nguoianphu-dns nguoianphu/docker-dns:9.9
  - docker ps -a
  - docker logs nguoianphu-dns
  - docker exec -it nguoianphu-dns named -v
  - docker exec -it nguoianphu-dns dig googole.com IN A
  - docker stop nguoianphu-dns
  
